package com.Labic.Comarca.TecladoWounMeu.utils;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class palabrasClass {
    public static ArrayList<String> palabrasSugeridas()
    {
        //TODO Leer de Archivo las Palabras y actualizar desde la web
        String palabras="Africapien\n" +
                "Americas\n" +
                "Américapieen\n" +
                "Articulo\n" +
                "Artículo\n" +
                "Bene\n" +
                "Beneeu\n" +
                "Bën\n" +
                "CSP/\n" +
                "Capítulo\n" +
                "Centro\n" +
                "Chadcha\n" +
                "Chaig\n" +
                "Chi\n" +
                "Colombiapieenauta\n" +
                "Como\n" +
                "DECRETA\n" +
                "Dauhaug\n" +
                "Dawaa\n" +
                "De\n" +
                "Decreto\n" +
                "Deeum\n" +
                "Degag\n" +
                "Dewam\n" +
                "DËN\n" +
                "Dëch\n" +
                "Ejecutivo\n" +
                "Estado\n" +
                "HIEEK\n" +
                "Haai\n" +
                "Haaita\n" +
                "Haayan\n" +
                "Haayau\n" +
                "Hag\n" +
                "Hagchaar\n" +
                "Hagjö\n" +
                "Hagjöopai\n" +
                "Hajuas\n" +
                "Hamach\n" +
                "Har\n" +
                "Hedau\n" +
                "Heskual\n" +
                "Hesãp\n" +
                "Hich\n" +
                "Hichi\n" +
                "Hichita\n" +
                "Hieek\n" +
                "Hieekꞌatarr\n" +
                "Hompaa\n" +
                "Honee\n" +
                "Hooba\n" +
                "Hooju\n" +
                "HÃBA\n" +
                "Hãb\n" +
                "Hãba\n" +
                "Hãba;\n" +
                "Hãbam\n" +
                "Hãbmieem\n" +
                "Hëwandamauta\n" +
                "Hõor\n" +
                "Hõorag\n" +
                "HĨGk’AA\n" +
                "Hĩsim\n" +
                "Hʌrrsiran\n" +
                "Hʌʌrrsir\n" +
                "Hʌ̃iba\n" +
                "Hẽwandam\n" +
                "Hẽwandamag\n" +
                "Hẽwandamauta\n" +
                "II\n" +
                "III\n" +
                "IV\n" +
                "JAAUTARR\n" +
                "JEMk’A\n" +
                "JUAPÁ\n" +
                "Jaauju\n" +
                "Jaautarr\n" +
                "Jaauwia\n" +
                "Jua\n" +
                "Juag\n" +
                "Jãdacha\n" +
                "Jãg\n" +
                "Jãga\n" +
                "Jãgata\n" +
                "Jãkꞌʌʌnauta\n" +
                "Jãp’ö\n" +
                "Jëeu\n" +
                "Jöoin\n" +
                "Jöoinau\n" +
                "Jöoyag\n" +
                "Jöoyau\n" +
                "Jʌã\n" +
                "K'augbam\n" +
                "Kolaau\n" +
                "K’ĩirhewagpäi\n" +
                "K’ũrr\n" +
                "Kꞌaigba\n" +
                "Kꞌapꞌʌ\n" +
                "Ley\n" +
                "Leyau\n" +
                "Ma\n" +
                "Maach\n" +
                "Maam\n" +
                "Maan\n" +
                "Maata\n" +
                "Macham\n" +
                "Mag\n" +
                "Magbamʌn\n" +
                "Magnaa\n" +
                "Magta\n" +
                "Magtarrta\n" +
                "Magua\n" +
                "Maguata\n" +
                "Maigmua\n" +
                "Maigta\n" +
                "Maimua\n" +
                "Monaau\n" +
                "Monaaujem\n" +
                "Mor\n" +
                "Mormachag\n" +
                "Mua\n" +
                "Mʌ\n" +
                "Mʌch\n" +
                "Mʌg\n" +
                "NEM\n" +
                "Naajem\n" +
                "Nacharam\n" +
                "Naciones\n" +
                "Nawe\n" +
                "Negöon\n" +
                "Nem\n" +
                "Nemjĩir\n" +
                "Ni\n" +
                "No\n" +
                "Nueva\n" +
                "Nʌʌ\n" +
                "Nʌʌpäi\n" +
                "OMS\n" +
                "OPS\n" +
                "OPS/OMS\n" +
                "OPSMor\n" +
                "P'ip'an\n" +
                "PATꞌEEG\n" +
                "Pabʌ̈\n" +
                "Padam\n" +
                "Panama\n" +
                "Panamapiem\n" +
                "Panamapien\n" +
                "Panamapienöjaauju\n" +
                "Panamapierr\n" +
                "Panamá\n" +
                "Paqnamá\n" +
                "Para\n" +
                "Pari\n" +
                "Potk’a\n" +
                "Potpa\n" +
                "Potpatarr\n" +
                "Pua\n" +
                "Pömaam\n" +
                "Pʌch\n" +
                "P’IGk’ARR\n" +
                "P’IP’AN:\n" +
                "P’ip’an\n" +
                "P’ip’anau\n" +
                "P’ÖBÖR\n" +
                "Pꞌatkꞌon\n" +
                "Pꞌëer\n" +
                "Pꞌöbör\n" +
                "Pꞌöbördam\n" +
                "República\n" +
                "SIIRAAG\n" +
                "SIIRJEM\n" +
                "SIIRk’AP’Ʌ\n" +
                "Siirjem\n" +
                "Tamburr\n" +
                "Tutub\n" +
                "T’ach\n" +
                "Tꞌetꞌem\n" +
                "Tꞌumaa\n" +
                "Tꞌumaam\n" +
                "Tꞌumwe\n" +
                "Tꞌʌag\n" +
                "Tꞌʌanaa\n" +
                "Tꞌʌ̃r\n" +
                "Unidas\n" +
                "WOUNAAN\n" +
                "Waarrgar\n" +
                "Waarrgarwe\n" +
                "Waauk’ap’ʌnaa\n" +
                "Wajapkꞌaba\n" +
                "Wajapꞌam\n" +
                "Warag\n" +
                "Warran\n" +
                "Warrgar\n" +
                "Warrgarm\n" +
                "Wau\n" +
                "Wauju\n" +
                "Wautarr\n" +
                "Wawaag\n" +
                "Woun\n" +
                "Wounaan\n" +
                "Ya\n" +
                "York\n" +
                "abril\n" +
                "abuelo\n" +
                "agosto\n" +
                "ahora\n" +
                "ak’aajem\n" +
                "articulo\n" +
                "artículo\n" +
                "at'ʌnajeejim\n" +
                "at’ʌ\n" +
                "b)\n" +
                "baarjem\n" +
                "baau\n" +
                "babawãg\n" +
                "bag\n" +
                "bagdam\n" +
                "bals\n" +
                "bar\n" +
                "baraag\n" +
                "barchëer\n" +
                "barchëju\n" +
                "barchëwia\n" +
                "barju\n" +
                "barpiba\n" +
                "barr\n" +
                "barrjeejim\n" +
                "barwia\n" +
                "bat’ẽe\n" +
                "bau\n" +
                "bawau\n" +
                "bebedö\n" +
                "bee\n" +
                "beenaa\n" +
                "beepieeg\n" +
                "beepimaaugau\n" +
                "beernaa\n" +
                "bem\n" +
                "ben\n" +
                "bene\n" +
                "benechaarkꞌa\n" +
                "beneeu\n" +
                "bieek\n" +
                "bigaau\n" +
                "bigawam\n" +
                "bri\n" +
                "burr\n" +
                "busca\n" +
                "bãau\n" +
                "bãaujö\n" +
                "bãaumam;\n" +
                "bãraa\n" +
                "bãraapain\n" +
                "bëejeejim\n" +
                "bëejem\n" +
                "bëenaa\n" +
                "bëepimkꞌõsi\n" +
                "bëer\n" +
                "bëerhʌch\n" +
                "bëewia\n" +
                "bëgaau\n" +
                "bënkꞌʌʌnau\n" +
                "bënë\n" +
                "bënëeu\n" +
                "bʌrnaajã\n" +
                "bʌrʌʌpäi\n" +
                "bʌʌ̃r\n" +
                "bʌ̃rʌʌ\n" +
                "bʌ̃ʌrjã\n" +
                "bʌ̈\n" +
                "bʌ̈gt’ʌ\n" +
                "bʌ̈jöo\n" +
                "bʌ̈rʌʌ\n" +
                "bӓjӓ\n" +
                "bӓjӓnaa\n" +
                "caja\n" +
                "cajon\n" +
                "capitulo\n" +
                "casete\n" +
                "casetes\n" +
                "cedro\n" +
                "centímetro\n" +
                "chaachjem\n" +
                "chaai\n" +
                "chaain\n" +
                "chaainaghawie\n" +
                "chaainau\n" +
                "chaainpa\n" +
                "chaar\n" +
                "chaar:\n" +
                "chaarau\n" +
                "chaarkꞌa\n" +
                "chaayau\n" +
                "chach\n" +
                "chadau\n" +
                "chadcha\n" +
                "chadcharam\n" +
                "chadcharan\n" +
                "chadchata\n" +
                "chagcharam\n" +
                "chan\n" +
                "charam\n" +
                "chdcharam\n" +
                "chi\n" +
                "chidau\n" +
                "chiita\n" +
                "chikꞌam\n" +
                "chipꞌam\n" +
                "chirajim\n" +
                "chirʌm\n" +
                "chog\n" +
                "chogaag\n" +
                "chogankꞌĩir\n" +
                "chogau\n" +
                "chogju\n" +
                "chogjö\n" +
                "chogmam\n" +
                "chognaa\n" +
                "chogp’öbaadeejierram\n" +
                "chogtarr\n" +
                "choogjeejim\n" +
                "choogjem\n" +
                "choogwäi\n" +
                "choonaa\n" +
                "choorbagk’a\n" +
                "chu\n" +
                "chuck’u\n" +
                "chugpaag\n" +
                "chugpapibanaa\n" +
                "chuk'u\n" +
                "chukö\n" +
                "chuk’u\n" +
                "chukꞌu\n" +
                "chukꞌum\n" +
                "chukꞌö\n" +
                "comarca\n" +
                "como\n" +
                "competentes\n" +
                "con\n" +
                "consulta\n" +
                "corta\n" +
                "creará\n" +
                "cubo\n" +
                "daau\n" +
                "daaugarjã\n" +
                "dabkꞌam\n" +
                "dag\n" +
                "dahí\n" +
                "daik’ierr\n" +
                "dak'a\n" +
                "dakpabaadeewäi\n" +
                "dak’a\n" +
                "dak’apäita\n" +
                "dakꞌĩir\n" +
                "dar\n" +
                "dasĩi\n" +
                "dau\n" +
                "daug\n" +
                "dauhap’am\n" +
                "dauhaug\n" +
                "dauju\n" +
                "daujöo\n" +
                "daujöu\n" +
                "dauná\n" +
                "daupeen\n" +
                "dawaa\n" +
                "dawaacha\n" +
                "dawaanaa\n" +
                "dawag\n" +
                "dawam\n" +
                "daíi\n" +
                "de\n" +
                "dee\n" +
                "deeimaju\n" +
                "deejem\n" +
                "deeju\n" +
                "deejumonaajem\n" +
                "deejö\n" +
                "deetarr\n" +
                "deeu\n" +
                "deeum\n" +
                "deeun\n" +
                "deg\n" +
                "degag\n" +
                "degam\n" +
                "degmua\n" +
                "del\n" +
                "desea\n" +
                "deum\n" +
                "deun\n" +
                "dewam\n" +
                "dewan\n" +
                "di\n" +
                "dificultad\n" +
                "disco\n" +
                "domeraan\n" +
                "domerjö\n" +
                "doojeejim\n" +
                "doowai\n" +
                "dule\n" +
                "duraa\n" +
                "durag\n" +
                "durr\n" +
                "durrag\n" +
                "durrum\n" +
                "dusnagau\n" +
                "duurrum\n" +
                "dë\n" +
                "dëch\n" +
                "dëchaagau\n" +
                "dëchdëu\n" +
                "dëchpijö\n" +
                "dëgolp\n" +
                "dën\n" +
                "dën)\n" +
                "dën:\n" +
                "dën?\n" +
                "dënan\n" +
                "dënau\n" +
                "dënauta\n" +
                "dëncha\n" +
                "dënchaar\n" +
                "dënchaau\n" +
                "dënjuta\n" +
                "dënjö\n" +
                "dënjöo\n" +
                "dënjöta\n" +
                "dënk’a\n" +
                "dënk’ayãu\n" +
                "dënkꞌa\n" +
                "dënma\n" +
                "dënpa\n" +
                "dënpai\n" +
                "dënpäita\n" +
                "dënta\n" +
                "dëná\n" +
                "dëu\n" +
                "dëupai\n" +
                "dëuta\n" +
                "dö\n" +
                "döbaag\n" +
                "dögaag\n" +
                "dögamkꞌĩir\n" +
                "dögju\n" +
                "döjuuijemta\n" +
                "döjãrg\n" +
                "döjãrr\n" +
                "döojem\n" +
                "dörröm\n" +
                "dösatagta\n" +
                "dötbaad\n" +
                "dʌhii\n" +
                "dʌi\n" +
                "dʌnʌwãag\n" +
                "dʌnʌʌubat\n" +
                "dʌnʌʌujö\n" +
                "dʌnʌʌunaa\n" +
                "dʌrpiju\n" +
                "dʌrrpiejeejim\n" +
                "dʌyëu\n" +
                "dʌʌrrʌʌ\n" +
                "dʌ̈i\n" +
                "dʌ̈i;\n" +
                "dʌ̈imua\n" +
                "dʌ̈ita\n" +
                "el\n" +
                "emberáwounaan\n" +
                "en\n" +
                "enero\n" +
                "especiales\n" +
                "espino\n" +
                "evitar\n" +
                "febrero\n" +
                "gaai\n" +
                "gaaijã\n" +
                "gaaim\n" +
                "gaaimua\n" +
                "gaaipäita\n" +
                "gaaita\n" +
                "galón\n" +
                "ganautarr\n" +
                "ganjö\n" +
                "garm\n" +
                "garpäi\n" +
                "gayam\n" +
                "ha\n" +
                "haadeewäi\n" +
                "haadëe\n" +
                "haadëjim\n" +
                "haadëp\n" +
                "haag\n" +
                "haagpai\n" +
                "haagpá\n" +
                "haai\n" +
                "haaidʌ\n" +
                "haaidʌag\n" +
                "haaidʌbaadëjĩ?\n" +
                "haaidʌju\n" +
                "haaidʌjö\n" +
                "haaidʌmam\n" +
                "haaidʌnaa\n" +
                "haaidʌtk’abaadëjim\n" +
                "haaidʌtkꞌa\n" +
                "haaidʌwia\n" +
                "haaipaba\n" +
                "haaipajeejim\n" +
                "haaipajim\n" +
                "haajeejim\n" +
                "haajeewäi\n" +
                "haajejim\n" +
                "haajem\n" +
                "haajemma\n" +
                "haajen\n" +
                "haajerr\n" +
                "haar\n" +
                "haaram\n" +
                "haarmua\n" +
                "haarr\n" +
                "haarrjö\n" +
                "haaug\n" +
                "haaujeejim\n" +
                "haaujem\n" +
                "haaujem;\n" +
                "haaujemjöo\n" +
                "haaumia\n" +
                "haawai\n" +
                "haawaita\n" +
                "haawäi\n" +
                "haawäijã\n" +
                "haawӓi\n" +
                "haawӓima\n" +
                "hab\n" +
                "haba\n" +
                "habaarwai:\n" +
                "habaawӓita\n" +
                "habam\n" +
                "habamag\n" +
                "habamʌg\n" +
                "habaraau\n" +
                "habarm\n" +
                "habá\n" +
                "hace\n" +
                "hacha\n" +
                "hachag\n" +
                "hachagk’am\n" +
                "hachcha\n" +
                "hachum\n" +
                "hadëjim\n" +
                "hag\n" +
                "hag:\n" +
                "hagcha\n" +
                "hagchaar\n" +
                "hagchaarau\n" +
                "hagdadaujö\n" +
                "hagdadaujöo\n" +
                "hagdamcha\n" +
                "hagdaujuu\n" +
                "hagdaujö\n" +
                "hagdaujöo\n" +
                "haggar\n" +
                "hagju\n" +
                "hagjum\n" +
                "hagjuu\n" +
                "hagjuunaa\n" +
                "hagjuupai\n" +
                "hagjö\n" +
                "hagjöm\n" +
                "hagjöo\n" +
                "hagjöokꞌam\n" +
                "hagjöopaim\n" +
                "hagjöopäi\n" +
                "hagjöpaim\n" +
                "hagjöu\n" +
                "hagjũrr\n" +
                "hagk’ãai\n" +
                "hagk’ʌʌrau\n" +
                "hagpierraa\n" +
                "hagpierram\n" +
                "hagt’a\n" +
                "hagua\n" +
                "haguee\n" +
                "hagueem\n" +
                "hagʌg\n" +
                "hagʌgcha\n" +
                "hagʌgpai\n" +
                "hagʌgpapai\n" +
                "hahaug\n" +
                "hahãbdö\n" +
                "haibëewi\n" +
                "haig\n" +
                "haigcha\n" +
                "haigmua\n" +
                "haigpai\n" +
                "hajap\n" +
                "hajapp'a\n" +
                "hajappai\n" +
                "hajapp’a\n" +
                "hajap’a\n" +
                "hajap’am\n" +
                "hajapꞌa\n" +
                "hajim\n" +
                "haju\n" +
                "haju)\n" +
                "hajunawe\n" +
                "hajuta\n" +
                "hajö\n" +
                "hajöes;\n" +
                "hajöta\n" +
                "hajöta:\n" +
                "hajú\n" +
                "hajũa\n" +
                "haka\n" +
                "hak’aar\n" +
                "hak’oopiba\n" +
                "hak’oopimaaugau\n" +
                "hakꞌa\n" +
                "hakꞌaardën\n" +
                "hakꞌaarpa\n" +
                "hakꞌajö\n" +
                "hakꞌãajem\n" +
                "halkol\n" +
                "ham\n" +
                "hamach\n" +
                "hamachdeüpai\n" +
                "hamachdëu\n" +
                "hamachpäita\n" +
                "hamau\n" +
                "hamdakꞌĩir\n" +
                "hamiet\n" +
                "hamk'ĩir\n" +
                "hamk’ĩir\n" +
                "hamkꞌĩir\n" +
                "hamkꞌĩirau\n" +
                "hamʌn\n" +
                "hanʌm\n" +
                "hap\n" +
                "hapaig\n" +
                "hapiba\n" +
                "hapieegpam\n" +
                "hapiju\n" +
                "hapijö\n" +
                "hapimaagau\n" +
                "hapimaaugau\n" +
                "hapmam\n" +
                "happai\n" +
                "happpäita\n" +
                "happäi\n" +
                "hapuraapai\n" +
                "hapöbaadeewäi\n" +
                "hap’ëp\n" +
                "har\n" +
                "harara\n" +
                "harrjim\n" +
                "hat\n" +
                "hatag\n" +
                "hatarr\n" +
                "hatarr)\n" +
                "hat’ee\n" +
                "hat’eem\n" +
                "hat’eepäyau\n" +
                "hat’oom\n" +
                "hat’ãrr\n" +
                "hat’ëe\n" +
                "hatꞌee\n" +
                "hatꞌeem\n" +
                "hatꞌeen\n" +
                "hau\n" +
                "hauba\n" +
                "haubam\n" +
                "haubanaa\n" +
                "haudʌtkꞌaju\n" +
                "haug\n" +
                "haujem\n" +
                "haujiierram\n" +
                "haujim\n" +
                "haujim:\n" +
                "hauju\n" +
                "haujö\n" +
                "haumaag\n" +
                "haumʌn\n" +
                "haunaa\n" +
                "haupi\n" +
                "hautaarran\n" +
                "hautarr\n" +
                "haut’uurjem\n" +
                "hauwi\n" +
                "hauwia\n" +
                "hawaan\n" +
                "hawaii\n" +
                "hawia\n" +
                "hawiajã\n" +
                "hawiajãhamach\n" +
                "he\n" +
                "hed\n" +
                "hedaram\n" +
                "hedau\n" +
                "hedausĩepӓita\n" +
                "hedawag\n" +
                "hedepierr\n" +
                "hedpai\n" +
                "hedp’errgarmua\n" +
                "hedta\n" +
                "hee\n" +
                "hee;\n" +
                "heechan\n" +
                "heeg\n" +
                "heegaa\n" +
                "heegar\n" +
                "heegpäita\n" +
                "heem\n" +
                "heem:\n" +
                "heemju\n" +
                "heempai\n" +
                "heemta\n" +
                "heemua\n" +
                "heepai\n" +
                "heepäi\n" +
                "heerpaba\n" +
                "heeta\n" +
                "heeu\n" +
                "heeuta\n" +
                "hegaapäi\n" +
                "hem\n" +
                "hemk’ooin\n" +
                "hemk’ooinau\n" +
                "hemk’ooinjã\n" +
                "hemk’ooinpa\n" +
                "hemk’ui\n" +
                "hemkꞌau\n" +
                "hemua\n" +
                "hep’ãichmie\n" +
                "heskual\n" +
                "heskuel\n" +
                "hestudieeg\n" +
                "hesãp\n" +
                "hesãpan\n" +
                "het\n" +
                "heudee\n" +
                "hewag\n" +
                "hewagam\n" +
                "hewagpawia\n" +
                "heyaa\n" +
                "heyaacha\n" +
                "hi\n" +
                "hich\n" +
                "hichdëu\n" +
                "hichdëupai\n" +
                "hichig\n" +
                "hichiita\n" +
                "hichk’um\n" +
                "hichmag\n" +
                "hichta\n" +
                "hichãb\n" +
                "hieek\n" +
                "hieekatarr\n" +
                "hieekau\n" +
                "hieektꞌeeg\n" +
                "hieekꞌa\n" +
                "hieekꞌaag\n" +
                "hieekꞌajem\n" +
                "hieekꞌaju\n" +
                "hieekꞌajö\n" +
                "hieekꞌarr\n" +
                "hieekꞌatarr\n" +
                "hieekꞌatarran\n" +
                "hieekꞌawai\n" +
                "hieekꞌawie\n" +
                "hiek\n" +
                "hiek’aba\n" +
                "hiekꞌaa\n" +
                "hiekꞌaajem\n" +
                "hiekꞌaju\n" +
                "hiekꞌanaa\n" +
                "hiekꞌarr\n" +
                "hiekꞌatarr\n" +
                "hiekꞌatarran\n" +
                "hiepajim\n" +
                "hierr\n" +
                "hig\n" +
                "higaau\n" +
                "higjö\n" +
                "higsimta\n" +
                "hiiekꞌa\n" +
                "hiiekꞌatarr\n" +
                "hiigjem\n" +
                "hiir\n" +
                "hiiu\n" +
                "hiiukꞌam\n" +
                "hinag\n" +
                "hipeyaa\n" +
                "hipeyaapäi\n" +
                "hipierra\n" +
                "hipirnaa\n" +
                "hisim\n" +
                "hitch\n" +
                "hit’eemau\n" +
                "hitꞌeem\n" +
                "hiwam\n" +
                "hiwiraata\n" +
                "hiyʌʌ\n" +
                "ho\n" +
                "hogaag\n" +
                "hogdʌba\n" +
                "hok’oo\n" +
                "hok’oopiba\n" +
                "hok’oopimaaugau\n" +
                "hokꞌoopiba\n" +
                "hompa\n" +
                "hompaa\n" +
                "hompaar\n" +
                "honee\n" +
                "honeem\n" +
                "hoo\n" +
                "hooba\n" +
                "hoobaawäi\n" +
                "hoog\n" +
                "hooimʌg\n" +
                "hooje\n" +
                "hoojem\n" +
                "hoojem;\n" +
                "hoojemau\n" +
                "hoojim\n" +
                "hooju\n" +
                "hoojuarraut\n" +
                "hooju´´\n" +
                "hoojö\n" +
                "hook’aajem\n" +
                "hook’ĩir\n" +
                "hookꞌa\n" +
                "hoom\n" +
                "hoomaag\n" +
                "hoomapꞌa\n" +
                "hoon\n" +
                "hoona\n" +
                "hoonaa\n" +
                "hoonʌʌ\n" +
                "hoopaar\n" +
                "hoopi\n" +
                "hoopieg\n" +
                "hoopiju\n" +
                "hoopijö\n" +
                "hoopimaaugau\n" +
                "hoorp'enaa\n" +
                "hoorp'epäaijem\n" +
                "hootarr\n" +
                "hoowai\n" +
                "hoowarrjö\n" +
                "hoowia\n" +
                "hoowäi\n" +
                "hora\n" +
                "huawia\n" +
                "hueco\n" +
                "hugua…\n" +
                "hurum\n" +
                "huröm\n" +
                "hãb\n" +
                "hãba\n" +
                "hãbam\n" +
                "hãbamʌg\n" +
                "hãban\n" +
                "hãbjã\n" +
                "hãbk’ai\n" +
                "hãbmua\n" +
                "hãbmuaja\n" +
                "hãd\n" +
                "hãdau\n" +
                "hãduanau\n" +
                "hãhãbdo\n" +
                "hãhãbdõ\n" +
                "hãhãbdö\n" +
                "hãhãddö\n" +
                "hãhãdö\n" +
                "hãjĩ\n" +
                "hãkõs\n" +
                "hãk’aajem\n" +
                "hãk’õs\n" +
                "hãkꞌa\n" +
                "hãkꞌaag\n" +
                "hãkꞌaajem\n" +
                "hãkꞌasĩerr\n" +
                "hãrjö\n" +
                "hãrpaaig\n" +
                "hãspa\n" +
                "hãspaapierr\n" +
                "hãspaapierrta\n" +
                "hãwãt\n" +
                "hé\n" +
                "hë\n" +
                "hëbaumie\n" +
                "hëchëu\n" +
                "hëerau\n" +
                "hëeu\n" +
                "hëeukꞌam\n" +
                "hëtꞌeem\n" +
                "hëu\n" +
                "hëua\n" +
                "hëudʌ\n" +
                "hëudʌba\n" +
                "hëudʌtk'a\n" +
                "hëudʌtk’aajem\n" +
                "hëutk'amamua\n" +
                "hëyʌʌ\n" +
                "hí\n" +
                "hõor\n" +
                "hõorag\n" +
                "hõoran\n" +
                "hõorau\n" +
                "hõorna\n" +
                "hõt\n" +
                "hö\n" +
                "höbër\n" +
                "höbërdʌtkꞌajö:\n" +
                "höbërdʌtkꞌamam\n" +
                "höbërkꞌĩir\n" +
                "höbërpimaaugau\n" +
                "höbërtarr\n" +
                "höbʌgju\n" +
                "höbʌgjöon\n" +
                "höchkꞌun\n" +
                "hödë\n" +
                "höhãba\n" +
                "hök’ar\n" +
                "hökꞌö\n" +
                "hökꞌönaa\n" +
                "höp’eeu\n" +
                "hörum\n" +
                "hörum:\n" +
                "höröm\n" +
                "hörömau\n" +
                "hösig\n" +
                "hösim\n" +
                "hĩgk’aa\n" +
                "hĩgk’aajaajeejim\n" +
                "hĩgk’aajeejim\n" +
                "hĩgk’atarr\n" +
                "hĩgkꞌajö\n" +
                "hĩgpa\n" +
                "hĩirtarr\n" +
                "hĩs\n" +
                "hĩsim\n" +
                "hĩsjã\n" +
                "hũaanpa\n" +
                "hũanaan\n" +
                "hũanpaawai\n" +
                "hũr\n" +
                "hũramk’ĩir\n" +
                "hũramk’ĩirau\n" +
                "hũrba\n" +
                "hũrbajö\n" +
                "hũurjem\n" +
                "hũurrjemjö\n" +
                "hʌ\n" +
                "hʌajim\n" +
                "hʌawai\n" +
                "hʌdʌraa\n" +
                "hʌgtaa\n" +
                "hʌgt’aa\n" +
                "hʌgt’aag\n" +
                "hʌgt’aagaapäi\n" +
                "hʌgt’aagar\n" +
                "hʌgtꞌaam\n" +
                "hʌiba\n" +
                "hʌk’a\n" +
                "hʌk’aajeejim\n" +
                "hʌk’aba\n" +
                "hʌkꞌaag\n" +
                "hʌkꞌaju\n" +
                "hʌm\n" +
                "hʌpäain\n" +
                "hʌpӓain\n" +
                "hʌr\n" +
                "hʌrch\n" +
                "hʌrcha\n" +
                "hʌrmuaj\n" +
                "hʌrrsir\n" +
                "hʌrta\n" +
                "hʌu\n" +
                "hʌuju\n" +
                "hʌukꞌabam\n" +
                "hʌukꞌëtꞌeem\n" +
                "hʌũanpa\n" +
                "hʌʌ\n" +
                "hʌʌajim\n" +
                "hʌʌi\n" +
                "hʌʌik’aan\n" +
                "hʌʌik’aar\n" +
                "hʌʌin\n" +
                "hʌʌinau\n" +
                "hʌʌinjã\n" +
                "hʌʌinpa\n" +
                "hʌʌrkꞌa\n" +
                "hʌʌyan\n" +
                "hʌʌyau\n" +
                "hʌ̃iba\n" +
                "hʌ̃r\n" +
                "hʌ̃rcha\n" +
                "hʌ̃rʌm\n" +
                "hʌ̃rʌmua\n" +
                "hᴧʌinjã\n" +
                "hẽkꞌa\n" +
                "hẽkꞌaagpam\n" +
                "hẽreu\n" +
                "hẽu\n" +
                "hẽwannaan\n" +
                "ideas\n" +
                "inaduledi\n" +
                "indígena\n" +
                "indígenas\n" +
                "jaaju\n" +
                "jaan\n" +
                "jaar\n" +
                "jaau\n" +
                "jaauba\n" +
                "jaaudedee\n" +
                "jaaudee\n" +
                "jaaudeegpam\n" +
                "jaaujeejim\n" +
                "jaaujem\n" +
                "jaaujemjö\n" +
                "jaaujerr\n" +
                "jaaujim\n" +
                "jaaujim:\n" +
                "jaauju\n" +
                "jaaujö\n" +
                "jaaukꞌaju\n" +
                "jaaumajö\n" +
                "jaaunaa\n" +
                "jaaunarram\n" +
                "jaaupʌajim\n" +
                "jaausiman\n" +
                "jaautarr\n" +
                "jaautarrjö\n" +
                "jaauwaag\n" +
                "jaauwai\n" +
                "jaauwäi\n" +
                "jaawaag\n" +
                "jaawaag:\n" +
                "jaga\n" +
                "jagata\n" +
                "jap\n" +
                "japdam\n" +
                "jar\n" +
                "jardam\n" +
                "jaujau\n" +
                "jawaag\n" +
                "jawaagan\n" +
                "jawaagpam\n" +
                "jawam\n" +
                "jawapꞌa\n" +
                "jayap\n" +
                "jayapam\n" +
                "jeeunaa\n" +
                "jeewaag\n" +
                "jemk'a\n" +
                "jemk'am\n" +
                "jemk’a\n" +
                "jemk’aa\n" +
                "jemk’aag\n" +
                "jemk’aajeejim\n" +
                "jemk’aajem\n" +
                "jemk’aajem;\n" +
                "jemk’aajerr\n" +
                "jemk’aajã\n" +
                "jemk’aajöo\n" +
                "jemk’aata\n" +
                "jemk’aau\n" +
                "jemk’ajö\n" +
                "jemk’am\n" +
                "jemk’amie\n" +
                "jemk’ut\n" +
                "jerag\n" +
                "jermua\n" +
                "jierr\n" +
                "jig\n" +
                "jigjö\n" +
                "jigkꞌʌʌiju\n" +
                "jigkꞌʌʌijö\n" +
                "jiirjopaag\n" +
                "jiiu\n" +
                "jiiuju\n" +
                "jiiunaa\n" +
                "jiiwaag\n" +
                "jirak\n" +
                "joo\n" +
                "jooba\n" +
                "joobaa\n" +
                "joobaajem\n" +
                "joobaje\n" +
                "joojem\n" +
                "joot'ʌag;\n" +
                "jootꞌʌpʌpʌig\n" +
                "jua\n" +
                "juaag\n" +
                "juachog\n" +
                "juachogaag;\n" +
                "juachogju\n" +
                "juachogjö\n" +
                "juag\n" +
                "juagam\n" +
                "juapa\n" +
                "juapatꞌeeg\n" +
                "juapatꞌetꞌe\n" +
                "juapá\n" +
                "juau\n" +
                "juauta\n" +
                "juchug\n" +
                "julio\n" +
                "junawe\n" +
                "junio\n" +
                "jupbaimá\n" +
                "jupchapai\n" +
                "jupꞌee\n" +
                "jupꞌeepai\n" +
                "juupjem\n" +
                "juventud\n" +
                "jágata\n" +
                "jã\n" +
                "jãg\n" +
                "jãga\n" +
                "jãgarmuajã\n" +
                "jãgata\n" +
                "jãgk’ʌʌr\n" +
                "jãgwia\n" +
                "jãk'ʌʌnauta\n" +
                "jãmagta\n" +
                "jãpʌinaa\n" +
                "jãp’ierrbaadëjim\n" +
                "jãp’ierrjö\n" +
                "jãp’u\n" +
                "jãp’ö\n" +
                "jãpꞌierrpiba\n" +
                "jãrr\n" +
                "jãrram\n" +
                "jëeu\n" +
                "jëeubat\n" +
                "jëeujeejim\n" +
                "jëeujeem\n" +
                "jëeujem\n" +
                "jëeujierram\n" +
                "jëeuju\n" +
                "jëeujö\n" +
                "jëeunaa\n" +
                "jëeunarr\n" +
                "jëeup’öbaadëmʌn\n" +
                "jëeusierr\n" +
                "jëeutarr\n" +
                "jëewaagpam\n" +
                "jëwaag\n" +
                "jëwamkꞌĩir\n" +
                "jõpa\n" +
                "jöoi\n" +
                "jöoin\n" +
                "jöoinau\n" +
                "jöoingarwe\n" +
                "jöokꞌam\n" +
                "jöopai\n" +
                "jöota\n" +
                "jĩgpa\n" +
                "jĩgpir\n" +
                "jĩir\n" +
                "jĩirdu\n" +
                "jĩirjöm\n" +
                "jĩirtarrjã\n" +
                "jĩpir\n" +
                "jũajëejim\n" +
                "jũrr\n" +
                "jũurjeman\n" +
                "jʌat’ʌtk’a\n" +
                "jʌgad\n" +
                "jʌgadau\n" +
                "jʌgatk’ahaug\n" +
                "jʌgã\n" +
                "jʌr\n" +
                "jʌrautarr\n" +
                "jʌrpʌijö\n" +
                "jʌssar\n" +
                "jʌssarnaa\n" +
                "jʌwamk’ĩir\n" +
                "jʌã\n" +
                "jʌʌat’ʌ\n" +
                "jʌʌrjem\n" +
                "jʌʌu\n" +
                "jʌ̃gaagaam\n" +
                "jʌ̃gad\n" +
                "jẽ\n" +
                "jẽb\n" +
                "jẽb;\n" +
                "jẽbaaga\n" +
                "jẽbag\n" +
                "jẽbʌcha\n" +
                "jẽert’ẽu\n" +
                "jẽgt’ẽupʌijö\n" +
                "jẽrpöd\n" +
                "jẽrpöt\n" +
                "jẽwãag\n" +
                "k'aba\n" +
                "k'abamʌn\n" +
                "k'ai\n" +
                "k'apeen\n" +
                "k'apeer\n" +
                "k'aperau\n" +
                "k'ariita\n" +
                "k'iirjuawain\n" +
                "k'u\n" +
                "k'ãijã\n" +
                "k'ëu\n" +
                "k'õ\n" +
                "k'õchagpierr\n" +
                "k'õchk'a\n" +
                "k'öojopnaa\n" +
                "k'ĩir\n" +
                "k'ʌʌnau\n" +
                "k'ẽu\n" +
                "kaba\n" +
                "kaigbam\n" +
                "kitõr\n" +
                "kokoordët\n" +
                "kokorrdit\n" +
                "kulãd\n" +
                "kuna\n" +
                "kõit\n" +
                "k’aag\n" +
                "k’aajem\n" +
                "k’aar\n" +
                "k’aba\n" +
                "k’abahab\n" +
                "k’abam\n" +
                "k’abamʌn\n" +
                "k’abasim\n" +
                "k’abata\n" +
                "k’aigbam\n" +
                "k’ainaan\n" +
                "k’ajũa\n" +
                "k’ak’apdönaa\n" +
                "k’apan\n" +
                "k’apank’aba\n" +
                "k’apeerau\n" +
                "k’apepp’ʌr\n" +
                "k’ap’ʌ\n" +
                "k’ap’ʌmpierr\n" +
                "k’au\n" +
                "k’aug\n" +
                "k’augba\n" +
                "k’augjĩ\n" +
                "k’augpʌiba\n" +
                "k’augtarr\n" +
                "k’eeupierr\n" +
                "k’eeurag\n" +
                "k’ek’eman\n" +
                "k’ierr\n" +
                "k’ipaar\n" +
                "k’ipaarau\n" +
                "k’itʌm\n" +
                "k’iyag\n" +
                "k’odnaan\n" +
                "k’odnaanaupäi\n" +
                "k’u\n" +
                "k’udak’a\n" +
                "k’ugwiu\n" +
                "k’ugwiwau\n" +
                "k’uju\n" +
                "k’ur\n" +
                "k’uu\n" +
                "k’uudʌ\n" +
                "k’ãai\n" +
                "k’ãaijem\n" +
                "k’ãijã\n" +
                "k’ãijũ\n" +
                "k’ãimaaugauta\n" +
                "k’ãyãu\n" +
                "k’ëeugurwe\n" +
                "k’ër\n" +
                "k’ëran\n" +
                "k’ërjim\n" +
                "k’õchag\n" +
                "k’õsi\n" +
                "k’õsimjöta\n" +
                "k’öojeejim\n" +
                "k’ör\n" +
                "k’ötarr\n" +
                "k’ĩet\n" +
                "k’ĩieta\n" +
                "k’ĩir\n" +
                "k’ĩirjũg\n" +
                "k’ĩirjũgau\n" +
                "k’ĩirjũgjã\n" +
                "k’ĩirjũnaajim\n" +
                "k’ĩirk’ap’ʌta\n" +
                "k’ĩirpierr\n" +
                "k’ĩirp’ee\n" +
                "k’ũrr\n" +
                "k’ũrrk’ãu\n" +
                "k’ʌdau\n" +
                "k’ʌʌn\n" +
                "k’ʌʌnau\n" +
                "k’ʌʌnjã\n" +
                "k’ẽu\n" +
                "k’ẽumii\n" +
                "kꞌa\n" +
                "kꞌaar\n" +
                "kꞌaarau\n" +
                "kꞌaarju\n" +
                "kꞌaba\n" +
                "kꞌabam\n" +
                "kꞌaigba\n" +
                "kꞌaigbag\n" +
                "kꞌaigbam\n" +
                "kꞌaisee\n" +
                "kꞌaiuta\n" +
                "kꞌam\n" +
                "kꞌaniuta\n" +
                "kꞌanta\n" +
                "kꞌap\n" +
                "kꞌapan\n" +
                "kꞌapcharam\n" +
                "kꞌapeerkꞌa\n" +
                "kꞌapi\n" +
                "kꞌapʌ\n" +
                "kꞌapꞌʌ\n" +
                "kꞌapꞌʌ:\n" +
                "kꞌapꞌʌm\n" +
                "kꞌapꞌʌmʌu\n" +
                "kꞌapꞌʌn\n" +
                "kꞌapꞌʌnaa\n" +
                "kꞌaug\n" +
                "kꞌaugaag\n" +
                "kꞌaugaan\n" +
                "kꞌaugam\n" +
                "kꞌaugau\n" +
                "kꞌaugbanarr\n" +
                "kꞌaugcha\n" +
                "kꞌaugcharam\n" +
                "kꞌaugjem\n" +
                "kꞌaugjö\n" +
                "kꞌaugmam\n" +
                "kꞌaugnaa\n" +
                "kꞌaugpiju\n" +
                "kꞌaugwai\n" +
                "kꞌodam\n" +
                "kꞌoggreu\n" +
                "kꞌoggreutarr\n" +
                "kꞌoojem\n" +
                "kꞌá\n" +
                "kꞌãai\n" +
                "kꞌãigper\n" +
                "kꞌãigpertarr\n" +
                "kꞌãigpërju\n" +
                "kꞌãigpërtarr\n" +
                "kꞌãijã\n" +
                "kꞌãiperju\n" +
                "kꞌër\n" +
                "kꞌërpꞌö\n" +
                "kꞌõchag\n" +
                "kꞌõchkꞌaba\n" +
                "kꞌõsi\n" +
                "kꞌõsim\n" +
                "kꞌõsĩnaa\n" +
                "kꞌĩe\n" +
                "kꞌĩiet\n" +
                "kꞌĩipierr\n" +
                "kꞌĩir\n" +
                "kꞌĩirheyaa\n" +
                "kꞌĩirheyaanaa\n" +
                "kꞌĩirjũ\n" +
                "kꞌĩirjũg\n" +
                "kꞌĩirjũg;\n" +
                "kꞌĩirjũgan\n" +
                "kꞌĩirjũgau\n" +
                "kꞌĩirjũgaupai\n" +
                "kꞌĩirjũgauta\n" +
                "kꞌĩirjũgpa\n" +
                "kꞌĩirjũgpata\n" +
                "kꞌĩirjũgta\n" +
                "kꞌĩirjũjũNacharam\n" +
                "kꞌĩirpierr\n" +
                "kꞌĩirpierram\n" +
                "kꞌĩirpierran\n" +
                "kꞌĩkꞌĩietdö\n" +
                "kꞌũgutꞌu\n" +
                "kꞌũwãg\n" +
                "kꞌʌ\n" +
                "kꞌʌʌg\n" +
                "kꞌʌʌmpa\n" +
                "kꞌʌʌn\n" +
                "kꞌʌʌnag\n" +
                "kꞌʌʌnan\n" +
                "kꞌʌʌnau\n" +
                "kꞌʌʌnauta\n" +
                "kꞌʌʌndaar\n" +
                "kꞌʌʌnpa\n" +
                "kꞌʌʌnta\n" +
                "kꞌʌʌu\n" +
                "la\n" +
                "largo\n" +
                "ley\n" +
                "los\n" +
                "ma\n" +
                "maach\n" +
                "maachdëmkꞌa\n" +
                "maachdëu\n" +
                "maadëu\n" +
                "maag\n" +
                "maagwai\n" +
                "maagwäiwe\n" +
                "maajeejim\n" +
                "maajem\n" +
                "maajen\n" +
                "maam\n" +
                "maan\n" +
                "maar\n" +
                "maata\n" +
                "maawӓi\n" +
                "maba\n" +
                "mach\n" +
                "macha\n" +
                "machag\n" +
                "machagauta\n" +
                "mag\n" +
                "magan\n" +
                "magbaa\n" +
                "magbam\n" +
                "magbamchan\n" +
                "magbamʌn\n" +
                "magban\n" +
                "magjim:\n" +
                "magju\n" +
                "magjã\n" +
                "magkꞌaita\n" +
                "magnaa\n" +
                "magta\n" +
                "magtarrk’ör\n" +
                "magua\n" +
                "maguaata\n" +
                "maguata\n" +
                "magwe\n" +
                "magʌm\n" +
                "maig\n" +
                "maigm\n" +
                "maigmua\n" +
                "maigta\n" +
                "maimua\n" +
                "majim\n" +
                "maju\n" +
                "mak’ʌʌn\n" +
                "makꞌʌʌnau\n" +
                "makꞌʌʌnauta\n" +
                "mam\n" +
                "mamkꞌĩir\n" +
                "mamua\n" +
                "mamʌ\n" +
                "manaaupaig\n" +
                "mapai\n" +
                "mapaita\n" +
                "mapiba\n" +
                "mapieeg\n" +
                "masat\n" +
                "masi\n" +
                "masim\n" +
                "masisierr\n" +
                "maweram\n" +
                "mayor\n" +
                "mediano\n" +
                "medicina\n" +
                "meejierram\n" +
                "meerjeejim\n" +
                "merapai\n" +
                "meu\n" +
                "meua\n" +
                "meukꞌaar\n" +
                "meun\n" +
                "miejö\n" +
                "mik\n" +
                "miuhap’a\n" +
                "mod\n" +
                "modelos\n" +
                "monaajem\n" +
                "monaau\n" +
                "monaaujem\n" +
                "monaaujem:\n" +
                "monaaujemOMS\n" +
                "monaaujemʌu\n" +
                "monaaujẽmau\n" +
                "monaaunaa\n" +
                "monaaupijö\n" +
                "monaaupʌimaag\n" +
                "monaawaag\n" +
                "monakꞌa\n" +
                "monakꞌa;\n" +
                "monakꞌam\n" +
                "monakꞌanaa\n" +
                "monaujem\n" +
                "mor\n" +
                "mordam\n" +
                "mork’arr\n" +
                "mormachag\n" +
                "mormasim\n" +
                "mua\n" +
                "má\n" +
                "mĩe\n" +
                "mʌ\n" +
                "mʌch\n" +
                "mʌg\n" +
                "mʌgta\n" +
                "mʌig\n" +
                "mʌiguim\n" +
                "mʌk’ʌʌnau:\n" +
                "mʌkꞌʌʌnta\n" +
                "mʌrʌ̃g\n" +
                "naag\n" +
                "naagmaag\n" +
                "naajem\n" +
                "naajerr\n" +
                "naajim\n" +
                "naaju\n" +
                "naaju:\n" +
                "naanau\n" +
                "naar\n" +
                "naaujem\n" +
                "naawiejã\n" +
                "nacha\n" +
                "nacharam\n" +
                "nacharamau\n" +
                "nachgarm\n" +
                "nachgarwe\n" +
                "napem\n" +
                "narrjö\n" +
                "naso\n" +
                "nawe\n" +
                "nawem\n" +
                "naweram\n" +
                "naweran\n" +
                "negöon\n" +
                "nele\n" +
                "nem\n" +
                "nem:\n" +
                "nemag\n" +
                "nemauta\n" +
                "nemek\n" +
                "nemeknaan\n" +
                "nemju\n" +
                "nemjõ\n" +
                "nemjĩi\n" +
                "nemjĩir\n" +
                "nemjĩir:\n" +
                "nemjĩirnaanau\n" +
                "nemk’oo\n" +
                "nemta\n" +
                "ngabe¬¬bugle\n" +
                "ni\n" +
                "no\n" +
                "noram\n" +
                "numi\n" +
                "numiim\n" +
                "numwe\n" +
                "nunwe\n" +
                "ná\n" +
                "náhkꞌõr\n" +
                "náhkꞌör\n" +
                "nʌ\n" +
                "nʌjö\n" +
                "nʌm\n" +
                "nʌm;\n" +
                "nʌmMormachag\n" +
                "nʌmauta\n" +
                "nʌmjã\n" +
                "nʌmjö\n" +
                "nʌmjöo\n" +
                "nʌmta\n" +
                "nʌmtꞌʌajen\n" +
                "nʌn\n" +
                "nʌnʌigdöm\n" +
                "nʌrraajeewai\n" +
                "nʌrraju\n" +
                "nʌrrʌmpierr\n" +
                "nʌtarr\n" +
                "nʌʌ\n" +
                "nʌʌrraajöo\n" +
                "p'ip'an\n" +
                "pa\n" +
                "paaiba\n" +
                "paamam\n" +
                "paardʌ\n" +
                "paarg\n" +
                "paarpa\n" +
                "paarpaju\n" +
                "paarpatarr\n" +
                "paarpawia\n" +
                "paau\n" +
                "paauk'achëwia\n" +
                "pabʌ\n" +
                "pabʌheem\n" +
                "pabʌ̈\n" +
                "pachaai\n" +
                "padam\n" +
                "padamau\n" +
                "paita\n" +
                "paker\n" +
                "pakꞌer\n" +
                "pakꞌër\n" +
                "pakꞌërau\n" +
                "pakꞌërnaan\n" +
                "pamãar\n" +
                "panamapieen\n" +
                "panamá\n" +
                "pap\n" +
                "para\n" +
                "paraa\n" +
                "parepat\n" +
                "parhoobam\n" +
                "parooban\n" +
                "patkꞌon\n" +
                "patkꞌonpai\n" +
                "patꞌeeg\n" +
                "peerdʌ\n" +
                "pekau\n" +
                "peraag\n" +
                "perik\n" +
                "perju\n" +
                "perjö\n" +
                "pespaajö\n" +
                "petá\n" +
                "pieen\n" +
                "pien\n" +
                "piirsinaa\n" +
                "pikiu\n" +
                "pital\n" +
                "pitkꞌajö\n" +
                "plåstico\n" +
                "podpa\n" +
                "pogkꞌe\n" +
                "pogkꞌë\n" +
                "potapau\n" +
                "potpa\n" +
                "potpawia\n" +
                "primeramente\n" +
                "pua\n" +
                "pueblos\n" +
                "pumk’aba\n" +
                "put\n" +
                "pãach\n" +
                "pãar\n" +
                "pãrhẽpkꞌaba\n" +
                "päart’ʌnaa\n" +
                "pëdau\n" +
                "përaag\n" +
                "përhaunaa\n" +
                "përju)\n" +
                "përjö\n" +
                "përmam\n" +
                "põm\n" +
                "pödpa\n" +
                "pödpaajem\n" +
                "pöm\n" +
                "pömaam\n" +
                "pömaamau\n" +
                "pömaan\n" +
                "pömag\n" +
                "pöorkꞌöu\n" +
                "pör\n" +
                "pörau\n" +
                "pörnaamag\n" +
                "pörnaan\n" +
                "pörnaan:\n" +
                "pörnaanau\n" +
                "pörnag\n" +
                "pöröu\n" +
                "pöt\n" +
                "pötpa\n" +
                "pʌ\n" +
                "pʌch\n" +
                "pʌchig\n" +
                "pʌiju\n" +
                "pʌinaa\n" +
                "pʌiwia\n" +
                "pʌr\n" +
                "pʌraag\n" +
                "pʌrjopjö\n" +
                "pʌrjökꞌaba\n" +
                "pʌrnaa\n" +
                "pʌrëu\n" +
                "pʌrʌg\n" +
                "pʌʌijem\n" +
                "pʌ̈ʌijem\n" +
                "p’eurg\n" +
                "p’iesta\n" +
                "p’ip'an\n" +
                "p’ip’am\n" +
                "p’ip’an\n" +
                "p’it’ur\n" +
                "p’ãp’ãrk’ë\n" +
                "p’õrr\n" +
                "p’öbör\n" +
                "p’öbörau\n" +
                "p’öbörjã\n" +
                "p’öorjem\n" +
                "p’öorjemua\n" +
                "p’öorsĩerr\n" +
                "p’örëe\n" +
                "p’ĩmaag\n" +
                "p’ʌ\n" +
                "p’ʌʌit’ʌ\n" +
                "p’ʌʌrdʌʌm\n" +
                "p’ẽeut’ʌ\n" +
                "p’ẽeut’ʌpäig\n" +
                "pꞌa\n" +
                "pꞌaba\n" +
                "pꞌagju\n" +
                "pꞌagnaat\n" +
                "pꞌai\n" +
                "pꞌaju\n" +
                "pꞌamam\n" +
                "pꞌanaa\n" +
                "pꞌatarr\n" +
                "pꞌatkꞌom\n" +
                "pꞌatkꞌonau\n" +
                "pꞌatkꞌondam\n" +
                "pꞌatkꞌõnau\n" +
                "pꞌidag\n" +
                "pꞌidkꞌaajem\n" +
                "pꞌidkꞌatarr\n" +
                "pꞌidkꞌatarr;\n" +
                "pꞌigkꞌa\n" +
                "pꞌigkꞌaajem\n" +
                "pꞌigkꞌaajemau\n" +
                "pꞌigkꞌaju\n" +
                "pꞌitkꞌa\n" +
                "pꞌitkꞌaag\n" +
                "pꞌitkꞌaagpam\n" +
                "pꞌitkꞌaajem\n" +
                "pꞌitkꞌaajem:\n" +
                "pꞌitkꞌaajemʌu\n" +
                "pꞌitkꞌaba\n" +
                "pꞌitkꞌag\n" +
                "pꞌitkꞌaju\n" +
                "pꞌitkꞌajö\n" +
                "pꞌitkꞌamkꞌõsinaa\n" +
                "pꞌitkꞌanaa\n" +
                "pꞌitkꞌawërjöm\n" +
                "pꞌitꞌurg\n" +
                "pꞌá\n" +
                "pꞌã\n" +
                "pꞌãajem\n" +
                "pꞌãartꞌʌ\n" +
                "pꞌãm\n" +
                "pꞌãmam\n" +
                "pꞌöbör\n" +
                "pꞌöbörau\n" +
                "pꞌöbördam\n" +
                "pꞌöbördën\n" +
                "pꞌöbörou\n" +
                "pꞌöbörpierr\n" +
                "pꞌöbörpierr;\n" +
                "pꞌöbörög\n" +
                "pꞌöböröu\n" +
                "pꞌör\n" +
                "pꞌörnaan\n" +
                "pꞌörnaanau\n" +
                "pꞌöurtꞌur\n" +
                "pꞌʌram\n" +
                "pꞌʌrdʌdʌ\n" +
                "pꞌʌrëu\n" +
                "pꞌʌrëum\n" +
                "pꞌʌʌrdʌ\n" +
                "pꞌʌʌrdʌju\n" +
                "que\n" +
                "respectivos\n" +
                "salud\n" +
                "se\n" +
                "seguridad\n" +
                "según\n" +
                "seman\n" +
                "septiembre\n" +
                "sieju\n" +
                "siejö\n" +
                "sigur\n" +
                "siir\n" +
                "siirba\n" +
                "siirjeejim\n" +
                "siirjeejim;\n" +
                "siirjem\n" +
                "siirjemau\n" +
                "siirjemʌu\n" +
                "siirju\n" +
                "siirwi\n" +
                "sim\n" +
                "sim:\n" +
                "sim;\n" +
                "siman\n" +
                "simau\n" +
                "simjö\n" +
                "simta\n" +
                "simʌn\n" +
                "sim…\n" +
                "sir\n" +
                "siraa\n" +
                "siraag\n" +
                "siraagpam\n" +
                "siram\n" +
                "sirba\n" +
                "sirbarmau\n" +
                "sirjö\n" +
                "sirnaa\n" +
                "sirtarrk’ur\n" +
                "sirwia\n" +
                "sisid\n" +
                "sisijuWarag\n" +
                "siëju\n" +
                "siẽeju\n" +
                "siẽjem\n" +
                "siẽju\n" +
                "social\n" +
                "suarreu\n" +
                "sukia\n" +
                "sãsãai\n" +
                "söhii\n" +
                "sĩejem\n" +
                "sĩejim\n" +
                "sĩeju\n" +
                "sĩejö\n" +
                "sĩemua\n" +
                "sĩerr\n" +
                "sĩerrʌm\n" +
                "sĩerta\n" +
                "sĩewäi\n" +
                "sĩi\n" +
                "sĩieb\n" +
                "sĩieta\n" +
                "sĩiujeejim\n" +
                "sĩiujem\n" +
                "sĩpag\n" +
                "sĩujem\n" +
                "sũrr\n" +
                "sꞌĩeju\n" +
                "t'et\n" +
                "t'uurk'apäaijem\n" +
                "t'ãu\n" +
                "t'ʌadʌba\n" +
                "tamaño\n" +
                "tambor\n" +
                "tamburr\n" +
                "tamburran\n" +
                "tamburrdam\n" +
                "tamburrjã\n" +
                "tamburrta\n" +
                "tiene\n" +
                "tocadisco\n" +
                "tocadłsco\n" +
                "tradicional\n" +
                "tʌʌ\n" +
                "tʌʌ̃\n" +
                "t’\n" +
                "t’ach\n" +
                "t’aik’ierrp\n" +
                "t’ak’aar\n" +
                "t’at’öoi\n" +
                "t’eeg\n" +
                "t’eer\n" +
                "t’eerjö\n" +
                "t’orrp’enaa\n" +
                "t’umaa\n" +
                "t’umaam\n" +
                "t’ut’apau\n" +
                "t’uud\n" +
                "t’ãrjũp\n" +
                "t’ãu\n" +
                "t’ʌaapnaa\n" +
                "t’ʌadʌt\n" +
                "t’ʌag\n" +
                "t’ʌap\n" +
                "t’ʌapaan\n" +
                "t’ʌapjem\n" +
                "t’ʌapjö\n" +
                "t’ʌapnaa\n" +
                "t’ʌapwäi\n" +
                "t’ʌap’em\n" +
                "t’ʌba\n" +
                "t’ʌbaajem\n" +
                "t’ʌbajim\n" +
                "t’ʌnʌm\n" +
                "t’ʌr\n" +
                "t’ʌʌrjem\n" +
                "t’ʌ̃r\n" +
                "t’ʌ̃rta\n" +
                "t’ʌ̃ʌrjem\n" +
                "t’ᴧadᴧt\n" +
                "tꞌaaba\n" +
                "tꞌaabapiejem\n" +
                "tꞌatꞌaarraa\n" +
                "tꞌeeg\n" +
                "tꞌet\n" +
                "tꞌetꞌem\n" +
                "tꞌetꞌemau\n" +
                "tꞌetꞌemnaan\n" +
                "tꞌum\n" +
                "tꞌumaa\n" +
                "tꞌumaam\n" +
                "tꞌumaan\n" +
                "tꞌumam\n" +
                "tꞌumwe\n" +
                "tꞌãrjũp\n" +
                "tꞌõojem\n" +
                "tꞌʌ\n" +
                "tꞌʌa\n" +
                "tꞌʌaag\n" +
                "tꞌʌaajem\n" +
                "tꞌʌajem\n" +
                "tꞌʌajemau\n" +
                "tꞌʌaju\n" +
                "tꞌʌajö\n" +
                "tꞌʌamam\n" +
                "tꞌʌanaa\n" +
                "tꞌʌapaar\n" +
                "tꞌʌawia\n" +
                "tꞌʌba\n" +
                "tꞌʌbabag\n" +
                "tꞌʌbaju\n" +
                "tꞌʌbarr\n" +
                "tꞌʌnaajö\n" +
                "tꞌʌnʌm\n" +
                "tꞌʌnʌmta\n" +
                "tꞌʌnʌn\n" +
                "tꞌʌr\n" +
                "tꞌʌwawaag\n" +
                "tꞌʌyʌu\n" +
                "tꞌʌʌg\n" +
                "tꞌʌ̃r\n" +
                "ua\n" +
                "un\n" +
                "uno\n" +
                "wa\n" +
                "waarju\n" +
                "waarr\n" +
                "waarraag\n" +
                "waarrgarpäi\n" +
                "waarrgarwe\n" +
                "waarrjem\n" +
                "waarrju\n" +
                "waarrömta\n" +
                "waaugpam\n" +
                "waaujeejim\n" +
                "waaujeerran\n" +
                "waaujem\n" +
                "waaujerr\n" +
                "waaujerran\n" +
                "waaujẽ\n" +
                "waauk’aug\n" +
                "waauwӓi\n" +
                "wai\n" +
                "waibëejeem\n" +
                "waibëejem\n" +
                "waibëetarran\n" +
                "waidurum\n" +
                "waiduurrum\n" +
                "waidëchjierram\n" +
                "waidëchjim\n" +
                "waidöraa\n" +
                "waidörum\n" +
                "waidöröm\n" +
                "waidöröm:\n" +
                "waidörömau\n" +
                "waidörömta\n" +
                "waidʌnʌm\n" +
                "waidʌnʌunaa\n" +
                "waidʌnʌwãag\n" +
                "waidʌnʌʌjö\n" +
                "waidʌnʌʌujem\n" +
                "waidʌnʌʌujö\n" +
                "wainaag\n" +
                "wainaag…¨;\n" +
                "wainaajeejim;\n" +
                "wainaajim\n" +
                "wainaaju\n" +
                "wainaajö\n" +
                "wainaamkꞌĩir\n" +
                "wainaarr\n" +
                "wainʌrrajö\n" +
                "wainʌ́\n" +
                "waisi\n" +
                "waisisit\n" +
                "waisiẽjö\n" +
                "waisĩieju:\n" +
                "waiwenʌrraag\n" +
                "waiwenʌrragHich\n" +
                "waiwenʌrrajö\n" +
                "waiwenʌʌrraju\n" +
                "wajap\n" +
                "wajapcha\n" +
                "wajapcharam\n" +
                "wajapcharamau\n" +
                "wajapcharamjuta\n" +
                "wajapcharan\n" +
                "wajapkꞌaba\n" +
                "wajapp’a\n" +
                "wajap’a\n" +
                "wajap’ata\n" +
                "wajapꞌa\n" +
                "wajapꞌag\n" +
                "wajapꞌakꞌaba\n" +
                "wajapꞌam\n" +
                "wajapꞌamau\n" +
                "wajapꞌamʌu\n" +
                "wajapꞌan\n" +
                "wajapꞌanaa\n" +
                "wajaug\n" +
                "wapꞌa\n" +
                "warag\n" +
                "waragcha\n" +
                "waragha\n" +
                "warp\n" +
                "warr\n" +
                "warre\n" +
                "warrju\n" +
                "warrpem\n" +
                "warrpemdam\n" +
                "warrtarr\n" +
                "warrum\n" +
                "wau\n" +
                "wauba\n" +
                "waubam\n" +
                "waubat\n" +
                "waubá\n" +
                "wauhaaug\n" +
                "waujim\n" +
                "wauju\n" +
                "wauju:\n" +
                "waujujã\n" +
                "waujö\n" +
                "waujöta\n" +
                "waujĩ\n" +
                "waukꞌaag\n" +
                "waukꞌĩir\n" +
                "waumaag\n" +
                "waumaju\n" +
                "waumajö\n" +
                "waumam\n" +
                "waumʌn\n" +
                "waunaa\n" +
                "waunkꞌĩir\n" +
                "waunʌm\n" +
                "waupaaig\n" +
                "waupʌi\n" +
                "waupʌpʌig\n" +
                "wausi\n" +
                "wausim\n" +
                "wautarr\n" +
                "wautarrkꞌai\n" +
                "wautꞌʌnʌʌujö\n" +
                "wauwenʌrraju\n" +
                "wauwia\n" +
                "wawaag\n" +
                "wawaagan\n" +
                "wawaagau\n" +
                "wawaagpam\n" +
                "wawagpam\n" +
                "wawam\n" +
                "wawan\n" +
                "wawiejem\n" +
                "wawë\n" +
                "wedurum\n" +
                "wedörum\n" +
                "wedörumkꞌʌʌn\n" +
                "wedöröm\n" +
                "weeudʌ\n" +
                "wejöm\n" +
                "wenʌrrag\n" +
                "wenʌrrajem\n" +
                "wenʌrraju\n" +
                "wenʌrrajurau\n" +
                "wenʌrraqju\n" +
                "werpʌaba\n" +
                "werpʌarr\n" +
                "weug\n" +
                "weuguee\n" +
                "weuwejum\n" +
                "wiguierr\n" +
                "wouanaan\n" +
                "woun\n" +
                "wounaan\n" +
                "wounaanau\n" +
                "wounaanaujã\n" +
                "wounau\n" +
                "wounaupӓi\n" +
                "wounta\n" +
                "wãwãkk’a\n" +
                "wãwãkꞌa\n" +
                "wënʌrraajem\n" +
                "wënʌrrar\n" +
                "wërbahimajim\n" +
                "wëtum\n" +
                "wʌrk'anaa\n" +
                "wʌrk’a\n" +
                "wʌwʌrʌʌk’am\n" +
                "wʌʌi\n" +
                "wʌʌmta\n" +
                "wʌ̈ʌ\n" +
                "ya\n" +
                "yẽtonaanag\n" +
                "yẽtonaanau\n" +
                "warag\n" +
                "K’an\n" +
                "Maach\n" +
                "ámbito\n" +
                "árbol\n" +
                "ťʌnaawäi\n" +
                "ʌʌ̃rjem\n" +
                "ʌ̃haaujem\n" +
                "̃perik";

        return convertirCadenaAArrayList(palabras);
    }
    private static ArrayList<String> convertirCadenaAArrayList(String cadena) {
        String[] palabras = cadena.split("\\s+|\n");
        // Convierte el array de palabras en un ArrayList
        ArrayList<String> listaPalabras = new ArrayList<>(Arrays.asList(palabras));

        return listaPalabras;
    }
}
